/*
Atividade 01: Crie uma Trigger que efetua baixa no Estoque do produto. 
*/
CREATE OR REPLACE TRIGGER triggerBaixaEstoque AFTER INSERT OR UPDATE ON ITEMPEDIDO
FOR EACH ROW WHEN (NEW.QUANTIDADE > 0)

DECLARE 
V_QTDATUAL NUMBER := 0;
V_BXESTOQUE NUMBER := 0;
BEGIN 
    SELECT QUANTIDADE INTO V_QTDATUAL FROM PRODUTO WHERE idproduto = :NEW.IDPRODUTO;
    
    V_BXESTOQUE := (V_QTDATUAL - :NEW.QUANTIDADE);
    UPDATE PRODUTO 
    SET QUANTIDADE = V_BXESTOQUE
    WHERE idproduto = :NEW.IDPRODUTO;
END;

/*
Atividade 02: Crie uma Trigger que gera log da baixa do produto. 
*/
CREATE OR REPLACE TRIGGER triggerLogProduto AFTER UPDATE ON PRODUTO 
FOR EACH ROW WHEN (NEW.QUANTIDADE > 0)

DECLARE 
V_ID NUMBER := 0;
BEGIN 

   SELECT COUNT(*)+1 INTO V_ID FROM LOG;
   INSERT INTO LOG (IDLOG, DATA, DESCRICAO) VALUES(V_ID,TO_DATE(SYSDATE,'DD/MM/YYYY'),('Baixa de Estoque -COD:'|| :NEW.IDPRODUTO ||' -PRODUTO: '||:NEW.DESCRICAO)); 
END;  
